### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by EvilOlaf** [gissehel/megacl#11]
Often an upload cancels with this error message:

```
Sending [350M] (367001600 bytes)
Traceback (most recent call last):
  File "/home/user/test/virtualenv-1.9/myVE/bin/mcl", line 8, in <module>
    if not(megaclclient.run( sys.argv )) :
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/cltools/configurable_runnable.py", line 68, in run
    return self.__super.run(args)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/cltools/runnable.py", line 185, in run
    self.parse(args)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/cltools/runnable.py", line 181, in parse
    command['code'](self,args=ordered_args,kwargs=dict_args)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/megacllib/commandline.py", line 507, in put
    api.upload(filename, node['h'])
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/mega/mega.py", line 526, in upload
    data=chunk, timeout=self.timeout)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/requests/sessions.py", line 354, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/test/virtualenv-1.9/myVE/lib/python2.7/site-packages/requests/adapters.py", line 246, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='gfs262n190.userstorage.mega.co.nz', port=80): Max retries exceeded with url: /ul/vcIGWDC44WdACQLKVmUbcE3_bPQrL4Igv3w3EZ9uaSBsT7XWjMaaTMucRyQSTb3bJ2gCl-ffSyHfFGsVFOVAZw/300417024 (Caused by <class 'httplib.BadStatusLine'>: '')
```

The urls and hosts are different every time.
Thats not a problem of megacl I guess, more a problem of connectivity, but don't know...

Olaf

**Comment by oiolong** [comment]
ha ha ... nobody fixed ... it's 2016 now
