### ISSUE TITLE
Can't download a file from mega.co.uz using megacl

### ISSUE THREAD

**Issue by vi** [gissehel/megacl#15]
```
$ ./megacl geturl 'https://mega.co.nz/#!OFEQ0Y4Z!0123456789wVrs6n7Jyx8-9876543210nkI8MA5Gf4g'
Downloading https://mega.co.nz/#!OFEQ0Y4Z!0123456789wVrs6n7Jyx8-9876543210nkI8MA5Gf4g
Traceback (most recent call last):
  File "./megacl", line 8, in <module>
    if not(megaclclient.run( sys.argv )) :
  File "/usr/local/lib/python2.7/dist-packages/cltools/configurable_runnable.py", line 68, in run
    return self.__super.run(args)
  File "/usr/local/lib/python2.7/dist-packages/cltools/runnable.py", line 185, in run
    self.parse(args)
  File "/usr/local/lib/python2.7/dist-packages/cltools/runnable.py", line 181, in parse
    command['code'](self,args=ordered_args,kwargs=dict_args)
  File "/mnt/src/git/megacl/megacllib/commandline.py", line 541, in geturl
    api.download_file(file_handle, file_key, is_public=True)
AttributeError: 'NoneType' object has no attribute 'download_file'
```

**Comment by evandrix** [comment]
facing the same issue here too - on MBP/Mac OSX 10.9.4

**Comment by gissehel** [comment]
Sorry, I don't actively maintain that tool since mega broke the old API. 
A lot of work should be done in order to make it works again, and I didn't put that effort yet.
Please consider this tool as obsolete.
